<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shared\Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="A2A"/>
        <PackageReference Include="A2A.AspNetCore"/>
    </ItemGroup>

</Project>
