<Project>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup Condition="'$(MSBuildProjectName)' != 'Shared' AND '$(MSBuildProjectName)' != 'PatternExplorer'">
        <Content Include="$(MSBuildThisFileDirectory)settings\appsettings.json">
            <Link>appsettings.json</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
