using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Agents;
using Shared;

var kernel = Settings.Kernel;

ChatCompletionAgent researcher = new()
{
    Name = "Researcher",
    Instructions = """
        You are a creative research scientist. Your role is to GENERATE novel hypotheses
        about a given topic. For each hypothesis:

        1. State the hypothesis clearly and concisely.
        2. Explain the reasoning — what existing knowledge supports this idea?
        3. Describe how it could be tested or validated.
        4. Rate your own confidence (low/medium/high).

        Generate 3 distinct hypotheses that vary in approach and boldness.
        Be creative — explore unconventional angles, not just obvious ideas.

        Format each hypothesis as:
        ## Hypothesis N: [title]
        **Claim**: ...
        **Reasoning**: ...
        **Testability**: ...
        **Confidence**: ...
        """,
    Kernel = kernel
};

ChatCompletionAgent critic = new()
{
    Name = "Critic",
    Instructions = """
        You are a rigorous scientific reviewer. Your role is to CRITICALLY EVALUATE
        hypotheses generated by a research team. For each hypothesis:

        1. Assess NOVELTY: Is this genuinely new, or a restatement of existing knowledge?
        2. Assess FEASIBILITY: Could this realistically be tested with current methods?
        3. Assess EVIDENCE: How well is it supported by existing literature?
        4. Identify WEAKNESSES: What are the gaps, assumptions, or potential flaws?
        5. Score it 1-10 on overall promise.

        Be constructive but rigorous. Don't accept vague claims.
        Identify the SINGLE most promising hypothesis and explain why.

        End with: "MOST PROMISING: Hypothesis N" and "OVERALL QUALITY: [low/medium/high]"
        """,
    Kernel = kernel
};

ChatCompletionAgent evolver = new()
{
    Name = "Evolver",
    Instructions = """
        You are a scientific strategist. Your role is to EVOLVE and REFINE hypotheses
        based on critical feedback. You receive:
        - The original hypotheses
        - A critic's evaluation with identified weaknesses

        Your task:
        1. Take the most promising hypothesis identified by the critic.
        2. Address each weakness the critic identified.
        3. Strengthen the reasoning and evidence.
        4. Explore one UNEXPECTED ANGLE — combine it with an idea from a different field.
        5. Produce a refined, stronger version of the hypothesis.

        Also produce ONE entirely new hypothesis inspired by the gaps the critic found.

        Format:
        ## Refined Hypothesis: [title]
        **Original weakness addressed**: ...
        **Improved claim**: ...
        **Cross-disciplinary insight**: ...
        **Confidence**: ...

        ## New Hypothesis: [title]
        **Inspired by gap**: ...
        **Claim**: ...
        """,
    Kernel = kernel
}; 

var topic = "What are novel approaches to reducing antibiotic resistance " +
            "in hospital settings that don't involve developing new antibiotics?";

const int maxIterations = 2; // Each iteration: generate -> critique -> evolve
string currentHypotheses = "";

Console.WriteLine($"Research Topic: {topic}\n");
Console.WriteLine(new string('-', 70));

for (int iteration = 1; iteration <= maxIterations; iteration++)
{
    Console.WriteLine($"\n{'-',0}--- Iteration {iteration}/{maxIterations} ---\n");
    
    Console.WriteLine("[Researcher] Generating hypotheses...\n");

    var genPrompt = iteration == 1
        ? $"Research topic: {topic}\n\nGenerate 3 novel hypotheses."
        : $"Research topic: {topic}\n\nPrevious round's evolved hypotheses:\n{currentHypotheses}\n\n" +
          "Build on these. Generate 3 NEW hypotheses that explore DIFFERENT directions.";

    string researcherOutput = "";
    await foreach (var chunk in researcher.InvokeAsync(genPrompt))
        researcherOutput += chunk.Message.Content;
    Console.WriteLine(researcherOutput);
    
    Console.WriteLine("\n\n[Critic] Evaluating hypotheses...\n");

    string criticOutput = "";
    await foreach (var chunk in critic.InvokeAsync(
        $"Research topic: {topic}\n\nHypotheses to evaluate:\n{researcherOutput}"))
        criticOutput += chunk.Message.Content;
    Console.WriteLine(criticOutput);
    
    if (criticOutput.Contains("OVERALL QUALITY: high", StringComparison.OrdinalIgnoreCase)
        && iteration > 1)
    {
        Console.WriteLine("\nHigh quality reached — stopping exploration.");
        break;
    }
    
    Console.WriteLine("\n\n[Evolver] Refining hypotheses...\n");

    string evolverOutput = "";
    await foreach (var chunk in evolver.InvokeAsync(
        $"Research topic: {topic}\n\n" +
        $"Original hypotheses:\n{researcherOutput}\n\n" +
        $"Critic's evaluation:\n{criticOutput}\n\n" +
        "Evolve the most promising hypothesis and generate one new one."))
        evolverOutput += chunk.Message.Content;
    Console.WriteLine(evolverOutput);

    currentHypotheses = evolverOutput;
}

// ----------------------------------------------
// 3. Final summary
// ----------------------------------------------

Console.WriteLine($"\n{'-',0}-- Final Discovery Summary ---\n");
Console.WriteLine("The exploration cycle has produced the following refined hypotheses:");
Console.WriteLine(currentHypotheses);
Console.WriteLine("\n?? These are AI-generated hypotheses requiring human validation and experimental verification.");